apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloudvault

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: cloudproject-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config

          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
              readOnly: true

          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cloudvault

spec:
  selector:
    app: backend

  ports:
    - port: 8000
      targetPort: 8000